const state={pokemonOptions:[],myParty:Array(6).fill(null),oppParty:Array(6).fill(null),myField:Array(3).fill(null),oppField:Array(3).fill(null),myActive:'',oppActive:''};
const S=id=>document.getElementById(id); const v=id=>S(id).value.trim();
async function init(){const r=await fetch('/api/pokemon_options');state.pokemonOptions=(await r.json()).options||[];render();}
function dataList(id){return `<datalist id='${id}'>${state.pokemonOptions.map(n=>`<option value='${n}'>`).join('')}</datalist>`;}
function evInputs(prefix,i){return ['H','A','B','C','D','S'].map(k=>`<input id='${prefix}_ev_${k}_${i}' placeholder='${k}'>`).join('');}
function card(prefix,i,full=true){return `<div class='card'><input list='pokeList' id='${prefix}_name_${i}' placeholder='名前'>${full?`<div class='row'>${evInputs(prefix,i)}</div><input id='${prefix}_nature_${i}' placeholder='性格'><input id='${prefix}_item_${i}' placeholder='持ち物'><input id='${prefix}_moves_${i}' placeholder='技1,技2,技3,技4'>`:''}</div>`;}
function fieldCard(side,i){const p=side==='my'?'m':'o';return `<div class='card' id='${side}card_${i}'><input list='pokeList' id='${p}f_name_${i}' placeholder='名前'><input id='${p}f_hp_${i}' placeholder='HP%'><input id='${p}f_status_${i}' placeholder='状態異常'><input id='${p}f_item_${i}' placeholder='判明持ち物(相手用)'><input id='${p}f_moves_${i}' placeholder='判明技(相手用: ,区切り)'><label><input type='checkbox' id='${p}f_mega_${i}'>メガ済</label><button onclick="setActive('${side}',${i})">選出中にする</button></div>`;}
function render(){S('myParty').innerHTML=dataList('pokeList')+Array.from({length:6},(_,i)=>card('my',i,true)).join('');S('oppParty').innerHTML=Array.from({length:6},(_,i)=>card('opp',i,false)).join('');S('oppParty').innerHTML+=dataList('pokeList');S('myField').innerHTML=Array.from({length:3},(_,i)=>fieldCard('my',i)).join('');S('oppField').innerHTML=Array.from({length:3},(_,i)=>fieldCard('opp',i)).join('');hookUsageOptions();}
function setActive(side,i){if(side==='my'){state.myActive=v(`mf_name_${i}`);[0,1,2].forEach(k=>S(`mycard_${k}`).classList.toggle('active',k===i));}else{state.oppActive=v(`of_name_${i}`);[0,1,2].forEach(k=>S(`oppcard_${k}`).classList.toggle('active',k===i));}}
function getEV(prefix,i){const o={};['H','A','B','C','D','S'].forEach(k=>o[k]=Number(v(`${prefix}_ev_${k}_${i}`)||0));return o;}
function readMyParty(){return Array.from({length:6},(_,i)=>({name:v(`my_name_${i}`),hp:100,status:'',fainted:false,item:v(`my_item_${i}`),moves:v(`my_moves_${i}`).split(',').map(x=>x.trim()).filter(Boolean),revealed_moves:[],mega_used:false,evs:getEV('my',i),nature:v(`my_nature_${i}`)}));}
function readOppParty(){return Array.from({length:6},(_,i)=>({name:v(`opp_name_${i}`),hp:100,status:'',fainted:false,item:'',moves:[],revealed_moves:[],mega_used:false,evs:{H:0,A:0,B:0,C:0,D:0,S:0},nature:''}));}
function readField(side){const p=side==='my'?'m':'o';return Array.from({length:3},(_,i)=>({name:v(`${p}f_name_${i}`),hp:Number(v(`${p}f_hp_${i}`)||100),status:v(`${p}f_status_${i}`),fainted:Number(v(`${p}f_hp_${i}`)||100)<=0,item:v(`${p}f_item_${i}`),moves:[],revealed_moves:v(`${p}f_moves_${i}`).split(',').map(x=>x.trim()).filter(Boolean),mega_used:S(`${p}f_mega_${i}`).checked,evs:{H:0,A:0,B:0,C:0,D:0,S:0},nature:''}));}
async function runSuggest(){const myParty=readMyParty();const oppParty=readOppParty();const myField=readField('my');const oppField=readField('opp');
const mergedMy=myParty.map(p=>myField.find(f=>f.name&&f.name===p.name)||p);const mergedOpp=oppParty.map(p=>oppField.find(f=>f.name&&f.name===p.name)||p);
const selected3=myField.map(x=>x.name).filter(Boolean);while(selected3.length<3)selected3.push('');
const payload={session_id:crypto.randomUUID(),my_party:mergedMy,opp_party:mergedOpp,selected3,my_active:state.myActive||selected3[0]||'',opp_active:state.oppActive||oppField.find(x=>x.name)?.name||'',weather:v('weather'),field:v('field'),turn:1};
const r=await fetch('/api/suggest',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();S('ai').textContent=j.error?j.error:JSON.stringify(j.suggestions,null,2);}
async function hookUsageOptions(){for(let i=0;i<6;i++){const el=S(`my_name_${i}`);el?.addEventListener('change',async()=>{const name=el.value.trim();if(!name)return;const r=await fetch(`/api/usage_options?name=${encodeURIComponent(name)}`);const u=await r.json();if(u.items?.length)S(`my_item_${i}`).placeholder='候補: '+u.items.slice(0,5).join('/');if(u.moves?.length)S(`my_moves_${i}`).placeholder='候補: '+u.moves.slice(0,4).join(',');if(u.natures?.length)S(`my_nature_${i}`).placeholder='候補: '+u.natures.slice(0,3).join('/');});}}
init();
