const state={my:[],opp:[],selected3:[],turn:1,session_id:crypto.randomUUID(),lastSuggestions:[],lastAction:null};
const val=id=>document.getElementById(id).value.trim();
const setLog=t=>document.getElementById('log').textContent=t;
const mkCard=(prefix,i,full)=>`<div class='card'><b>${i+1}</b><input id='${prefix}name${i}' placeholder='名前'>${full?`<input id='${prefix}hp${i}' placeholder='HP%'><input id='${prefix}status${i}' placeholder='状態異常'><input id='${prefix}item${i}' placeholder='持ち物'><input id='${prefix}moves${i}' placeholder='技1,技2,技3,技4'>`:''}</div>`;
document.getElementById('my').innerHTML=Array.from({length:6},(_,i)=>mkCard('m',i,true)).join('');
document.getElementById('opp').innerHTML=Array.from({length:6},(_,i)=>mkCard('o',i,true)).join('');
document.getElementById('sel').innerHTML=[0,1,2].map(i=>`<input id='sel${i}' placeholder='選出${i+1}'>`).join('');
function p(prefix,i){const hp=Number(val(prefix+'hp'+i)||100);return {name:val(prefix+'name'+i),hp,status:val(prefix+'status'+i),fainted:hp<=0,item:val(prefix+'item'+i),moves:val(prefix+'moves'+i).split(',').map(s=>s.trim()).filter(Boolean),revealed_moves:[],mega_used:false};}
function saveMy(){state.my=Array.from({length:6},(_,i)=>p('m',i)); if(state.my.some(x=>!x.name)) return setLog('自分6匹の名前をすべて入力してください'); state.selected3=[state.my[0].name,state.my[1].name,state.my[2].name]; ['sel0','sel1','sel2'].forEach((id,i)=>document.getElementById(id).value=state.selected3[i]); setLog('自分パーティ保存 + 選出初期値を自動セット');}
function saveOpp(){state.opp=Array.from({length:6},(_,i)=>p('o',i)); if(state.opp.some(x=>!x.name)) return setLog('相手6匹の名前をすべて入力してください'); setLog('相手パーティ保存');}
function saveSel(){state.selected3=[val('sel0'),val('sel1'),val('sel2')]; if(state.selected3.some(x=>!x)) return setLog('選出3匹をすべて入力してください'); setLog('選出保存');}
function payload(){return {my_party:state.my,opp_party:state.opp,selected3:state.selected3,my_active:val('myActive'),opp_active:val('oppActive'),weather:val('weather'),field:val('field'),turn:state.turn,top_k:5};}
async function suggest(){const r=await fetch('/api/suggest',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload())});const j=await r.json();if(j.error){setLog('提案エラー: '+j.error);return;}state.lastSuggestions=j.suggestions;document.getElementById('ai').textContent=j.suggestions.map((s,i)=>`${i+1}. ${s.action.kind}:${s.action.name}${s.action.mega?'(メガ)':''} score=${s.score} / ${s.why}`).join('\n');state.lastAction=j.suggestions[0]?.action||null;setLog('AI提案を更新');}
function applyTopSuggestion(){if(!state.lastAction) return setLog('先にAI提案を実行してください'); setLog(`採用候補: ${state.lastAction.kind}:${state.lastAction.name}${state.lastAction.mega?'(メガ)':''}`);}
async function saveTurn(){const r=await fetch('/api/save_turn',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...payload(),session_id:state.session_id,last_action:state.lastAction})});const j=await r.json();if(j.error){setLog(j.error);return;}state.turn++;setLog(`turn保存:${j.turns}`);}
async function saveResult(){if(!state.lastAction){setLog('先にAI提案を実行し、行動候補を決めてください');return;}const resultLabel=val('result');const win=resultLabel==='win';const r=await fetch('/api/record_result',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({session_id:state.session_id,my_active:val('myActive'),action:state.lastAction,win,result_label:resultLabel})});const j=await r.json();setLog(j.error||`対戦結果送信完了: ${resultLabel==='win'?'勝ち':'負け'}`);}
async function resetBattle(){const r=await fetch('/api/reset_battle',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({session_id:state.session_id,my_party:state.my})});const j=await r.json();if(j.ok){state.opp=[];state.selected3=[];state.turn=1;state.lastAction=null;state.lastSuggestions=[];document.getElementById('ai').textContent='';setLog('リセット完了(自分パーティ維持)');}}

async function loadStats(){const r=await fetch('/api/model_stats');const j=await r.json();document.getElementById('meta').textContent=JSON.stringify(j,null,2);}
async function loadHistory(){const r=await fetch('/api/history');const j=await r.json();document.getElementById('meta').textContent=JSON.stringify(j,null,2);}
